.TH "Cell" 3 "Wed Oct 25 2017" "Version 0.1" "Numerical Hydrodynamics MPI+CUDA Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cell
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBr\fP"
.br
.ti -1c
.RI "double \fBu\fP"
.br
.ti -1c
.RI "double \fBv\fP"
.br
.ti -1c
.RI "double \fBe\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file cell\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Numerical Hydrodynamics MPI+CUDA Project from the source code\&.
