.TH "DynamicLibraryVisualization/UnitTests/UnitTestTriangle/drawSimpleField.cpp" 3 "Wed Oct 25 2017" "Version 0.1" "Numerical Hydrodynamics MPI+CUDA Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicLibraryVisualization/UnitTests/UnitTestTriangle/drawSimpleField.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'interface\&.h'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'cell\&.h'\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <dlfcn\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBmapToInterval\fP (uint64_t val, uint64_t max)"
.br
.ti -1c
.RI "uint64_t \fBrand_congr\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint64_t \fBp\fP = 2147483647"
.br
.ti -1c
.RI "uint64_t \fBc\fP = 16807"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 34 of file drawSimpleField\&.cpp\&.
.SS "double mapToInterval (uint64_t val, uint64_t max)"

.PP
Definition at line 21 of file drawSimpleField\&.cpp\&.
.SS "uint64_t rand_congr ()"

.PP
Definition at line 27 of file drawSimpleField\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "uint64_t c = 16807"

.PP
Definition at line 19 of file drawSimpleField\&.cpp\&.
.SS "uint64_t p = 2147483647"

.PP
Definition at line 18 of file drawSimpleField\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Numerical Hydrodynamics MPI+CUDA Project from the source code\&.
