.TH "DynamicLibraryVisualization/FieldObject.cpp" 3 "Wed Oct 25 2017" "Version 0.1" "Numerical Hydrodynamics MPI+CUDA Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicLibraryVisualization/FieldObject.cpp \- This file contains descriptions of functions (\fBFieldObject\fP class methods) which are responsible for rendering the field and storing all necessary environmental variables\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FieldObject\&.hpp'\fP
.br
\fC#include 'shader\&.h'\fP
.br
\fC#include <exception>\fP
.br
\fC#include 'cell\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "GLuint \fBprogramID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains descriptions of functions (\fBFieldObject\fP class methods) which are responsible for rendering the field and storing all necessary environmental variables\&. 


.PP
\fBAuthor:\fP
.RS 4
Eugene Kolesnikov 
.RE
.PP
\fBDate:\fP
.RS 4
8/10/2017 
.RE
.PP

.PP
Definition in file \fBFieldObject\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Numerical Hydrodynamics MPI+CUDA Project from the source code\&.
