.TH "logging" 3 "Wed Oct 25 2017" "Version 0.1" "Numerical Hydrodynamics MPI+CUDA Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logging
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileLogger\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFileLogger\fP & \fBoperator<<\fP (\fBFileLogger\fP &logger, const \fBFileLogger::e_logType\fP l_type)"
.br
.ti -1c
.RI "\fBFileLogger\fP & \fBoperator<<\fP (\fBFileLogger\fP &logger, const char *text)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBFileLogger\fP& logging::operator<< (\fBFileLogger\fP & logger, const \fBFileLogger::e_logType\fP l_type)"

.PP
Definition at line 28 of file FileLogger\&.cpp\&.
.SS "\fBFileLogger\fP& logging::operator<< (\fBFileLogger\fP & logger, const char * text)"

.PP
Definition at line 46 of file FileLogger\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Numerical Hydrodynamics MPI+CUDA Project from the source code\&.
