.TH "DynamicLibraryVisualization/MainWindow.cpp" 3 "Wed Oct 25 2017" "Version 0.1" "Numerical Hydrodynamics MPI+CUDA Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicLibraryVisualization/MainWindow.cpp \- This file contains descriptions of functions (\fBMainWindow\fP class methods) which are responsible for all necessary functions related to the window itself: creation, termination, events handling, cleaning\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'MainWindow\&.hpp'\fP
.br
\fC#include <exception>\fP
.br
\fC#include <OpenGL/gl3\&.h>\fP
.br
\fC#include 'offscreen\&.h'\fP
.br

.SH "Detailed Description"
.PP 
This file contains descriptions of functions (\fBMainWindow\fP class methods) which are responsible for all necessary functions related to the window itself: creation, termination, events handling, cleaning\&. 


.PP
\fBAuthor:\fP
.RS 4
Eugene Kolesnikov 
.RE
.PP
\fBDate:\fP
.RS 4
8/10/2017 
.RE
.PP

.PP
Definition in file \fBMainWindow\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Numerical Hydrodynamics MPI+CUDA Project from the source code\&.
